/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.io.IOException;
import javax.swing.JOptionPane;
import clases.*;



/**
 *
 * @author Javier
 */
public class login extends javax.swing.JFrame {

    empleado emp = new empleado();
    empleadodao empdao = new empleadodao();

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
        entrar.requestFocus();
    }
    /**
     * clase validar, nos permite la validacion de un usario al iniciar sesion
     * permitiendo unicamente a los empleaso registradso en el sistema el inicio de sesion
     * en este mismo, mediante un JoptionPane soltamos un comunicado de error en el caso
     * de que el nombre de usuario (nombre del empleado) o la contraseña sea incottectas
     */
    public void validar(){
        String nombre = usuario.getText();
        String contraseña = String.valueOf(contraseñaa.getPassword());
        
        //mediante un if coprpbamos que los campos de texto nombre y contraselña no esten vacios
        if (!"".equals(nombre) || !"".equals(contraseña)) {
            //obtenemos los datos de un determinado empleado mediante las clases login y logindao
            //para esto empleamos el metodo log de la clase logindao
            Login_1 lg = new Login_1();
            LoginDao login = new LoginDao();
            lg = login.log(nombre, empdao.Encriptar(contraseña));
            //comprobamso que hemos recuperado el nombre y la contraseña de un usuario
            if (lg.getNombre() != null && lg.getContraseña() != null) {
                //comprobamos su rango dentro de la empresa
                if (!"admin".equals(lg.getRango())) {
                    sistema sis = new sistema();
                    sis.setVisible(true);
                    dispose();
                } else {
                    sistemaadmins sis = new sistemaadmins();
                    sis.setVisible(true);
                    dispose();
                }
                
            } else {
                //mensaje de error que saltara en caso de que la contraseña sea incorrecta
                JOptionPane.showMessageDialog(null, "contraseña o usuario incprrecta");
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        entrar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        contraseñaa = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        fondo.setBackground(new java.awt.Color(102, 102, 102));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/usuario.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cerrar-con-llave.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 122, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 180, -1));

        usuario.setBackground(new java.awt.Color(102, 102, 102));
        usuario.setText("EMPLEADO");
        usuario.setBorder(null);
        usuario.setOpaque(false);
        usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usuarioFocusLost(evt);
            }
        });
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        jPanel2.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 154, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("INICIO DE SESION");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 6, -1, -1));

        entrar.setBackground(new java.awt.Color(204, 255, 204));
        entrar.setText("INICIO");
        entrar.setBorder(null);
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        jPanel2.add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 90, 40));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 180, 20));

        contraseñaa.setBackground(new java.awt.Color(102, 102, 102));
        contraseñaa.setText("******");
        contraseñaa.setBorder(null);
        contraseñaa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contraseñaaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contraseñaaFocusLost(evt);
            }
        });
        contraseñaa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contraseñaaMousePressed(evt);
            }
        });
        jPanel2.add(contraseñaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 152, 30));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setText("MANUAL DE USUARIO");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 130, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 370, 370));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fruteria (1).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 6, -1, -1));

        jLabel6.setText("sistema de gestion de ventas");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 467, -1, -1));

        jLabel7.setText("trabajo final programacion ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 489, -1, -1));

        jLabel8.setText("Javier Rodrioguez Garrido");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 511, -1, -1));

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 170, 540));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        jLabel4.setText("FRUTAS Y VERDURAS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        fondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -6, 540, 190));

        getContentPane().add(fondo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed
    /**
     * boton entrar de la pestaña login, nos permite activar el metodo validar escrito encima de este
     * @param evt 
     */
    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_entrarActionPerformed

    /**
     * metodo encargado de que al pulsar el boton del manual de usuario
     * este se muestre por tapalla
     * para esto se empleao un runtine.getruntine y el cmd de windows
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String doc = "src/documentacion/documentacion.pdf";
        try {
            Runtime.getRuntime().exec("cmd /c start " + doc);
        } catch (IOException e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioFocusGained
        // TODO add your handling code here:
        usuario.setText("");
    }//GEN-LAST:event_usuarioFocusGained

    private void usuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioFocusLost
        // TODO add your handling code here:
        if ("".equals(usuario.getText())) {
            usuario.setText("EMPLEADO");
        }
    }//GEN-LAST:event_usuarioFocusLost

    private void contraseñaaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseñaaFocusGained
        // TODO add your handling code here:
        
            contraseñaa.setText("");
        
    }//GEN-LAST:event_contraseñaaFocusGained

    private void contraseñaaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseñaaFocusLost
        // TODO add your handling code here:
        if ("".equals(String.valueOf(contraseñaa.getPassword()))) {
            contraseñaa.setText("******");
        }
    }//GEN-LAST:event_contraseñaaFocusLost

    private void contraseñaaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñaaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseñaa;
    private javax.swing.JButton entrar;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
